 function sampleText(){
     return(
         <div style={{backgroundColor: "red"}}>
         <h1>
             Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id iaculis tellus, quis dignissim nulla. Phasellus sit amet nulla et enim tempus tempor. Nullam id hendrerit massa, eu volutpat quam. Nunc rhoncus, tortor at pretium consectetur, ex diam vestibulum ante, non tincidunt sem massa eget ligula. Integer neque lacus, sodales nec mollis in, pellentesque auctor neque. Sed libero nibh, ornare nec dolor in, elementum vulputate mi. Mauris placerat ac mauris vel convallis.

Sed sed ex et leo sagittis tempus sit amet et odio. Sed eu lacinia justo, a tempor sem. Nunc nec ipsum volutpat urna volutpat scelerisque a non orci. Maecenas gravida neque vel elit pulvinar molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus risus odio, fermentum ac elit at, commodo auctor est. Integer lacinia libero dui, et pretium justo fringilla id. Sed pretium, leo sit amet fermentum convallis, tortor nunc mattis urna, nec placerat nisi sapien et dui. Integer vitae neque sem.

Vivamus ullamcorper tincidunt erat in feugiat. Nulla vitae metus nec orci efficitur semper. Cras luctus sed metus id rutrum. Donec ut justo id tellus consequat congue. Duis laoreet lacus nec turpis mattis venenatis. Praesent iaculis feugiat eleifend. Quisque vel augue ipsum. Aenean sagittis lobortis diam non vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla iaculis leo et luctus mattis. Praesent vitae lorem erat.

Sed rutrum auctor nisi euismod laoreet. Sed eget odio facilisis, vulputate nunc vitae, tincidunt augue. Curabitur posuere pellentesque urna, a malesuada erat accumsan in. Donec quis libero ut turpis consequat consectetur id non dolor. Donec vitae elit sed nisi elementum aliquam at a sem. Integer finibus sodales dui. Integer vel purus nisi. Praesent ligula ipsum, sodales aliquam ultricies luctus, bibendum vel dolor. Ut sit amet arcu mi. Sed tempus accumsan erat, quis iaculis libero pretium quis. Fusce libero libero, ullamcorper vitae orci non, pulvinar mollis enim. Curabitur dignissim condimentum tincidunt. Mauris est libero, cursus sit amet magna sed, vehicula euismod magna. Curabitur molestie imperdiet lorem at lobortis. Fusce nec metus suscipit, venenatis ipsum sit amet, dictum turpis. Nulla interdum, risus elementum vehicula dapibus, velit odio maximus tortor, placerat luctus justo metus vitae leo.

Fusce turpis nibh, rutrum vitae egestas et, aliquam in quam. Vestibulum auctor et erat et scelerisque. Maecenas vitae mi a elit tempus tristique. Aliquam erat volutpat. Cras mattis ante in nibh porttitor, id ornare felis cursus. Nullam sit amet tincidunt nunc, eget tincidunt lorem. Sed convallis hendrerit feugiat. Quisque vestibulum eros vitae dui fringilla dapibus. Integer ac viverra quam. Sed posuere ipsum id maximus porta. Duis eu elit ac orci blandit dignissim. Sed ultricies purus eu eros finibus malesuada. Nullam in faucibus tellus, at auctor nunc.

Ut condimentum condimentum risus quis pellentesque. Nullam imperdiet sollicitudin lorem at lacinia. Maecenas laoreet enim non massa facilisis dignissim. Pellentesque risus est, accumsan et aliquet sed, fermentum eget dolor. Ut mollis erat justo, eu congue est iaculis eu. In porta et eros eu posuere. Nam pharetra purus ut sem mattis semper. Phasellus dictum pellentesque faucibus. In hac habitasse platea dictumst. Nunc interdum nec nibh a pretium. In lacinia vulputate eros, bibendum fermentum velit semper nec. Donec aliquet velit at enim interdum scelerisque. Morbi augue ante, bibendum a molestie in, elementum non nisi.

Mauris dictum sapien at sapien accumsan, ac luctus ipsum laoreet. Nullam vitae luctus libero, id pretium nisi. Donec faucibus varius tortor, non scelerisque erat tincidunt eget. Phasellus viverra orci non ligula egestas lacinia. Fusce a sem sed lacus interdum consequat. Curabitur at diam eu lacus mollis rhoncus at nec ligula. Donec vulputate porttitor mattis. Quisque vestibulum felis ac purus scelerisque ullamcorper. Integer aliquet ultricies neque eu sodales. Nunc in facilisis tellus. Duis sit amet mauris id ligula vulputate suscipit aliquet vitae enim. Pellentesque non nibh egestas, ullamcorper ex id, ultrices tellus. Sed luctus sagittis cursus. Cras efficitur ex sit amet arcu euismod, quis volutpat elit vehicula. In dui lorem, rhoncus quis laoreet quis, molestie eu neque.

Vestibulum porttitor porta nunc a rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eu libero ut velit maximus ultrices. Maecenas elit felis, volutpat ac metus at, gravida iaculis nulla. Aenean porttitor nisl dignissim, varius tellus vitae, semper magna. Nam in leo eu odio tincidunt egestas. Cras at libero tortor. Morbi mattis, nibh eget rutrum aliquam, magna urna ornare purus, tincidunt placerat arcu nulla nec nunc. Aliquam congue, quam at convallis lobortis, elit purus elementum eros, eget mollis tortor dolor id nisi. Integer sit amet libero nec augue imperdiet dignissim.

Quisque fermentum ullamcorper diam ut dictum. Etiam tempus pharetra urna, ac imperdiet massa ultricies in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus interdum augue sem, ut tincidunt velit consectetur eget. Integer ac eleifend ante. Etiam vitae nisi ac augue varius luctus a et lorem. Vestibulum justo enim, congue id lacinia quis, posuere id justo. Nam in nulla id orci feugiat faucibus eu nec nisl. Curabitur elementum suscipit urna eu tincidunt. Integer dolor odio, vehicula et maximus eu, ultrices in ipsum. Sed viverra sagittis finibus.

Nullam quam nibh, commodo id ex non, sollicitudin posuere elit. Suspendisse finibus malesuada mi. Praesent luctus lectus odio, sed consectetur tellus placerat tincidunt. Pellentesque eu elit nec est mollis dignissim et vitae est. Fusce auctor ultrices purus, nec pulvinar nulla consectetur et. Suspendisse aliquet, felis eu feugiat volutpat, mi tortor consectetur libero, gravida pulvinar sem neque id magna. Mauris fringilla nisi diam, et lobortis velit efficitur a. Quisque semper id metus vitae porttitor. Vivamus ultricies, lacus at dignissim vestibulum, dui dui posuere mauris, eget ultricies est ante ut massa. Donec urna leo, fringilla non nisi id, hendrerit feugiat turpis. Vivamus ut mauris sed dolor mattis mollis. Quisque lacinia eros felis, non viverra nisl maximus in. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In gravida ex tellus, nec tempor elit sollicitudin eu.
         </h1>
         </div>
     );
 }

 export default sampleText;